name = input("what is your name? ")
print("Hello, ", name)
Feeling = input("How are you feeling today, Good or bad?")
print("I am happy today")
stuff = input("what do you like to do?")
print("I also like", stuff)
print("")
